server:
  #端口号
  port: 1111
spring:
  application: eurka-server
#  security:
#    user:
#      name: admin
#      password: ${MONITOR_SERVER_PASSWORD:admin}
eureka:
  instance:
    #needed to trigger info and endpoint update after restart
    #设置当前实例的主机名称
    hostname: localhost
  client:
    #启动服务注册
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，
    #不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000
    #定义服务续约任务（心跳）的调用间隔，单位：秒
    lease-renewal-interval-in-seconds: 6



