#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/
server:
  port: 8072
spring:
  application:
    name: order-service

    #由于spring-boot-starter-data-elasticsearch 占时支持6.8以下版本。
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
#  elasticsearch:
#    rest:
#      uris: ["http://127.0.0.1:9200"]
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true
#      properties:
#        transport:
#              tcp:
#                #连接超时的时间
#                connect_timeout: 120s
score-thread-pool:
  core: 10
  maximum: 30
  queue: 80000

