server:
  port: 8093
  servlet:
    context-path: /resources

#\u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    health-check-url-path: /actuator/health   #\u5E94\u7528\u5B9E\u4F8B\u7684\u76F8\u5BF9\u8FD0\u884C\u72B6\u51B5\u68C0\u67E5URL\u8DEF\u5F84\u9ED8\u8BA4\u4E3A /info/health

spring:
  application:
    name: order-service
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/xml
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response:
      enabled: true

#logging:
#  config: classpath:logback-spring.xml
#  level:
#    root: warn
#    com.mp.dao: trace
#  pattern:
#    console:  '%p%m%n'

