server:
  port: 8000
  servlet:
    context-path: /oauth2

spring:
  application:
    name: oauth
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    health-check-url-path: /actuator/health   #应用实例的相对运行状况检查URL路径默认为 /info/health
  zipkin:
    base-url: http://localhost:9411


jedis:
  address: 127.0.0.1
  port: 6379
  auth:
  maxIdle: 100
  maxActive: 300
  maxWait: 10000
  testOnBorrow: true